spring:
  application:
    name: datenportal-sodata

datenportal:
  catalog:
    source: classpath:published_catalog_full_54_entries.xtf
  search:
    max-results: 500
    default-page-size: 20
    max-page-size: 100
  web-components:
    enabled: true
    version: "0.1.9"
    asset-base-path: "/vendor/so-web-components/0.1.9"
    use-cdn: false

gg:
  jte:
    development-mode: true
